<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="4.3.0" />
    <PackageReference Include="UnicornEngine.Unicorn" Version="2.0.2" />
    <PackageReference Include="Microsoft.Z3" Version="4.12.2" />
  </ItemGroup>

</Project>
